"""water: a small WebAssembly Text Format parser and emitter."""

from .ast import (
    ArithmeticInstruction,
    ArithmeticOperation,
    Call,
    ComparisonInstruction,
    ComparisonOperation,
    Constant,
    Function,
    FunctionImport,
    Index,
    Instruction,
    Local,
    Module,
    NumericalType,
    NumericalValue,
    Parameter,
    Program,
    ScopeKind,
    Type,
    Unreachable,
    VariableInstruction,
    VariableOperation,
)
from .emitter import Emitter
from .leb128 import encode_signed_leb128, encode_unsigned_leb128

__all__ = [
    "ArithmeticInstruction",
    "ArithmeticOperation",
    "Call",
    "ComparisonInstruction",
    "ComparisonOperation",
    "Constant",
    "Emitter",
    "Function",
    "FunctionImport",
    "Index",
    "Instruction",
    "Local",
    "Module",
    "NumericalType",
    "NumericalValue",
    "Parameter",
    "Program",
    "ScopeKind",
    "Type",
    "Unreachable",
    "VariableInstruction",
    "VariableOperation",
    "encode_signed_leb128",
    "encode_unsigned_leb128",
]
